AmeWeb/Controllers/CaptureCardsController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AmeCommon.CardsCapture;
using AmeWeb.Model;
using Microsoft.AspNetCore.Mvc;

namespace AmeWeb.Controllers
{
    public class CaptureCardsController : Controller
    {
        private readonly ICaptureProjectCooridinator captureCooridinator;
        private readonly IAmeProjectRepository projectRepo;

        public CaptureCardsController(ICaptureProjectCooridinator captureCooridinator, IAmeProjectRepository projectRepo)
        {
            this.captureCooridinator = captureCooridinator;
            this.projectRepo = projectRepo;
        }

        public IActionResult Index(string projectPath)
        {
            var model = new CaptureCardsViewModel();
            var project = projectRepo.GetProject(projectPath);
            model.Project = project;
            model.AvaliableCommands = captureCooridinator.GetAavaliableDeviceCommands(project);
            return View(model);
        }

        public IActionResult StartCapture(string projectPath, List<SelectedCommands> devices, bool svn, string template)
        {
            var project = projectRepo.GetProject(projectPath);
            var selectedDrives = devices.Where(d => d.Selected).Select(d => new DriveInfo(d.Drive));
            var commandId = captureCooridinator.StartCapture(project, template, selectedDrives, svn);
            return RedirectToAction(nameof(HomeController.ShowAmeTask), "Home", new { id = commandId });
        }

        public IActionResult ShowConflicts(string projectPath, string sourceDrive)
        {
            var project = projectRepo.GetProject(projectPath);
            var device = captureCooridinator.CreateCommand(new DriveInfo(sourceDrive), project.GetLocalPathRoot());
            return View(device);
        }
    }
}

AmeWeb/Controllers/DevicesController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using AmeCommon.CardsCapture;
using AmeCommon.Model;
using AmeWeb.Model;
using Microsoft.AspNetCore.Mvc;

namespace AmeWeb.Controllers
{
    public class DevicesController : Controller
    {
        private IAmeProjectRepository repository;
        private readonly IDeviceManager deviceManager;
        private readonly ICaptureProjectCooridinator captureCooridinator;

        public DevicesController(IAmeProjectRepository repository, IDeviceManager deviceManager, ICaptureProjectCooridinator captureCooridinator)
        {
            this.repository = repository;
            this.deviceManager = deviceManager;
            this.captureCooridinator = captureCooridinator;
        }

        public IActionResult Index()
        {
            return View(ScanDevices());
        }

        private List<CardInfoViewModel> ScanDevices()
        {
            var model = DriveInfo.GetDrives()
                .Where(d => d.IsReady && d.DriveType == DriveType.Removable)
                .Select(d => new CardInfoViewModel
                {
                    Device =
                        captureCooridinator.GetDevice(d) ??
                        new Device {Id = 0, UniqueName = "unknown", Captures = new List<DeviceCaptureInfo>()},
                    InsertedInDrive = d.Name
                })
                .ToList();

            var allStoredDevices = deviceManager.GetAllDevices();
            foreach (var d in allStoredDevices)
            {
                if (model.All(modelDevice => modelDevice.Device.Id != d.Id))
                    model.Add(new CardInfoViewModel {Device = d});
            }
            return model;
        }

        public IActionResult DeviceEdit(int deviceId, string drive)
        {
            var device = string.IsNullOrEmpty(drive) ? 
                deviceManager.GetDevice(deviceId) :
                captureCooridinator.GetDevice(new DriveInfo(drive));
            var model = new CardInfoViewModel
            {
                Device = device ?? new Device { Id = 0, UniqueName = "unknown", Captures = new List<DeviceCaptureInfo>() },
                InsertedInDrive = drive,
            };
            return View(model);
        }

        public IActionResult AssignDevice(int deviceId, string drive)
        {
            var device = deviceManager.GetDevice(deviceId);
                var doc = new XDocument(
                    new XElement(XName.Get("ame-card", "http://kamerzysta.bydgoszcz.pl"),
                        new XElement(XName.Get("id", "http://kamerzysta.bydgoszcz.pl"), device.UniqueName)
                    ));
                doc.Save(Path.Combine(drive, "ame.xml"));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteDeviceAssociation(string drive)
        {
            System.IO.File.Delete(Path.Combine(drive, "ame.xml"));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult SaveDevice(CardInfoViewModel model)
        {
            var device = model.Device;
            device.Captures.RemoveAll(cmd => string.IsNullOrEmpty(cmd.SourceMask));
            deviceManager.UpdateDevice(device);
            if (!string.IsNullOrEmpty(model.InsertedInDrive))
            {
                var doc = new XDocument(
                    new XElement(XName.Get("ame-card", "http://kamerzysta.bydgoszcz.pl"),
                        new XElement(XName.Get("id", "http://kamerzysta.bydgoszcz.pl"), model.Device.UniqueName)
                    ));
                doc.Save(Path.Combine(model.InsertedInDrive, "ame.xml"));
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteDevice(int id)
        {
            deviceManager.RemoveDevice(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AmeWeb/Controllers/HomeController.cs
using System;
using System.Linq;
using AmeCommon.CardsCapture;
using AmeCommon.Tasks;
using AmeCommon.VideoMonitoring;
using AmeWeb.Model;
using Microsoft.AspNetCore.Mvc;

namespace AmeWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAmeProjectRepository projectRepo;
        private readonly ITasksManager tasksManager;
        private readonly IVideoGrabber video;

        public HomeController(IAmeProjectRepository projectRepo, ITasksManager tasksManager, IVideoGrabber video)
        {
            this.projectRepo = projectRepo;
            this.tasksManager = tasksManager;
            this.video = video;
        }

        public IActionResult Index()
        {
            var model = new HomeViewModel
            {
                Projects = projectRepo.AllProjects(),
                DestiantionRoot = projectRepo.LocalSettings.SelectedProjectsRootPath,
                Tasks = tasksManager.GetAllTasks(),
            };
            return View(model);
        }

        public IActionResult ShowAmeProject(string projectPath)
        {
            var project = projectRepo.GetProject(projectPath);
            return View(project);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
        
        public IActionResult ChangeRootDirectory()
        {
            projectRepo.ChangeRootDirectory();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateProject(DateTime projectDate, string projectName)
        {
            var proj = projectRepo.CreateProject(projectDate, projectName);
            return RedirectToAction(nameof(Index), "CaptureCards", new { projectPath = proj.LocalPathRoot });
        }

        public IActionResult ShowAmeTask(Guid id)
        {
            return View(tasksManager.GetTask(id));
        }

        public IActionResult GetAmeTaskState(Guid id)
        {
            var task = tasksManager.GetTask(id);
            var model = new
            {
                State = task.State.ToString(),
                Times = $"{task.StarTime} - {task.EndTime}",
                ChildTasks = task.ChildTasks.Select(ct =>
                        new
                        {
                            ct.Id,
                            State = ct.State.ToString()
                        }
                ).ToList()
            };

            return Json(model);
        }
    }
}

AmeWeb/Views/CaptureCards/Index.cshtml
@using System.Threading.Tasks
@using AmeWeb.Model
@model CaptureCardsViewModel
@{
    ViewData["Title"] = "AME Home Page";
}

<div class="row">
    <h2>Projekt: @Model.Project.UniqueName</h2>
    <h4>@Model.Project.LocalPathRoot</h4>
    @if (Model.AvailableFreeDiskSpace <= Model.RequiredDiskSpace)
    {
        var avaliable = Model.AvailableFreeDiskSpace.DisplayFileSize();
        var required = Model.RequiredDiskSpace.DisplayFileSize();
        <h4 class="bg-danger">Uwaga niewystarczająca ilość wolnego miejsca! Wolne miejsce: @avaliable Wymagane: @required</h4>
    }

    <form asp-action="StartCapture">
        @Html.Hidden("projectPath", Model.Project.LocalPathRoot)
        <table class="table table-condensed table-bordered">
            <tr>
                <th></th>
                <th>Urządzenie</th>
                <th>Dysk</th>
                <th>Info</th>
            </tr>
            @for (var i = 0; i < Model.AvaliableCommands.Count; i++)
            {
                var device = Model.AvaliableCommands[i];
                var hasWarning = device.GetAllConflictWithStoredFiles().Any();
                var trClass = hasWarning ? "bg-danger" : "";
                var deviceImagePath = $"images/{device.Label}.jpg";
                <tr class="@trClass">
                    <td>
                        @Html.CheckBox($"devices[{i}].Selected", device.FilesCount > 0)
                        @Html.Hidden($"devices[{i}].Drive", device.SourceDrive)
                    </td>
                    <td><img src="@deviceImagePath" style="height: 75px"/>@device.Label</td>
                    <td>@device.SourceDrive</td>
                    <td class="DeviceInfo">
                        <div>Pliki: @device.FilesCount Rozmiar: @device.FilesSize.DisplayFileSize()</div>
                        <div>
                            @if (hasWarning)
                            {
                                @Html.ActionLink("Uwaga! Wykryto konflikt z istniejącymi plikami.", "ShowConflicts", new { projectPath = Model.Project.LocalPathRoot, device.SourceDrive }, new { style = "font-weight: bold" })
                            }
                        </div>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="4">
                    <div>
                        <img src="images/resources.jpg" style="height: 20px" />
                        <label for="template">Szablon: </label>
                        <select id="template" name="template">
                            <option value="Wesele" selected>Wesele</option>
                            <option value="Przedszkole">Przedszkole</option>
                            <option value="">Inne</option>
                        </select>
                    </div>
                    <div>
                        <img src="images/svn.jpg" style="height: 20px" />
                        <label for="svn">Utwórz repozytorium SVN</label>
                        @Html.CheckBox("svn", true)
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="4"><input type="submit" value="Rozpocznij kopiowanie"/></td>
            </tr>
        </table>
    </form>
</div>

AmeWeb/Views/CaptureCards/ShowConflicts.cshtml
@model AmeCommon.CardsCapture.DeviceMoveFileCommands
@{
    ViewData["Title"] = "AME Project";
}

@{ var imagePath = $"/images/{Model.Device.UniqueName}.jpg"; }
<img src="@imagePath" style="height: 75px" />
<table class="table table-condensed table-bordered">
    <tr>
        <th></th>
        <th>Nazwa</th>
        <th>plik źródłowy</th>
        <th>plik docelowy</th>
    </tr>
    @foreach (var cmd in Model.Commands)
    {
        var trClass = cmd.DestinationFile.Exists ? "bg-danger" : "bg-success";
        <tr class="@trClass">
            <td></td>
            <td>@cmd.File.RelativePath</td>
            <td>
                @if (cmd.SourceFile.Exists)
                {
                    @cmd.SourceFile.Length
                }
            </td>
            <td>@if (cmd.DestinationFile.Exists)
                {
                    @cmd.DestinationFile.Length
                }
            </td>
        </tr>
    }
</table>

AmeWeb/Views/Devices/DeviceEdit.cshtml
@using System.Threading.Tasks
@using AmeWeb.Model
@model CardInfoViewModel
@{
    ViewData["Title"] = "AME Home - Urządzenie";
}

<div class="row">
    <form asp-action="SaveDevice">
        @Html.HiddenFor(m => m.Device.Id)
        @Html.HiddenFor(m => m.InsertedInDrive)
        @{ var imagePath = $"/images/{Model.Device.UniqueName}.jpg"; }
        <h2>
            <img src="@imagePath" style="height: 75px"/>
            @Html.TextBoxFor(m => m.Device.UniqueName)
        </h2>
        <span>Aktualnie w napędzie: <b>@Model.InsertedInDrive</b></span>
        <table class="table table-condensed table-bordered">
            <tr>
                <th>Polecenie</th>
                <th>Zródło</th>
                <th>Cel</th>
            </tr>
            @for (int i=0; i<Model.Device.Captures.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DropDownListFor(m => m.Device.Captures[i].Command, CardInfoViewModel.AvaliableCommands)
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.Device.Captures[i].SourceMask)
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.Device.Captures[i].TargetFolder)
                    </td>
                </tr>
            }
            
            @for (int i = Model.Device.Captures.Count; i < Model.Device.Captures.Count+4; i++)
            {
                <tr>
                    <td>
                        @Html.DropDownList($"Device.Captures[{i}].Command", CardInfoViewModel.AvaliableCommands)
                    </td>
                    <td>
                        @Html.TextBox($"Device.Captures[{i}].SourceMask", "")
                    </td>
                    <td>
                        @Html.TextBox($"Device.Captures[{i}].TargetFolder", "")
                    </td>
                </tr>
            }
        </table>
        <input type="submit" value="Zapisz"/>
        @Html.ActionLink("Anuluj", "Index")
    </form>
</div>

AmeWeb/Views/Devices/Index.cshtml
@using System.Threading.Tasks
@using AmeWeb.Model
@model List<CardInfoViewModel>
@{
    ViewData["Title"] = "AME Home - Lista urządzeń";
}

<div class="row">
    <table class="table table-condensed table-bordered">
        <tr>
            <th></th>
            <th></th>
            <th>Urządzenie</th>
            <th>Dysk</th>
            <th>Opis operacji</th>
            <th>Akcja</th>
        </tr>
        @foreach (var device in Model)
        {
            var trClass = device.InsertedInDrive!=null ? "bg-success" : "bg-normal";
            var imagePath = $"/images/{device.Device.UniqueName}.jpg";
            <tr class="@trClass">
                <td></td>
                <td><img src="@imagePath" style="height: 75px"/></td>
                <td>
                    @if (device.Device.Id != 0)
                    {
                        @Html.ActionLink(device.Device.UniqueName, "DeviceEdit", new {deviceId = device.Device.Id, drive = device.InsertedInDrive})
                    }
                    else if (!string.IsNullOrEmpty(device.InsertedInDrive))
                    {
                        @Html.ActionLink("Dodaj nowe urządzenie", "DeviceEdit", new { deviceId = device.Device.Id, drive = device.InsertedInDrive })<br/>
                        <span>Przypisz</span>
                        <form asp-action="AssignDevice">
                            @Html.Hidden("drive", device.InsertedInDrive)
                            @Html.DropDownList("deviceId", Model.Where(d => d.Device.Id != 0).Select(d => new SelectListItem {Text = d.Device.UniqueName, Value = d.Device.Id.ToString()}), "", new {onchange = "$(this).parent('form:first').submit();"})
                        </form>
                    }
                </td>
                <td>
                    @device.InsertedInDrive
                    @if (!string.IsNullOrEmpty(device.InsertedInDrive))
                    {
                        @Html.ActionLink("Usuń przypisanie do urządzenia", "DeleteDeviceAssociation", new {drive = device.InsertedInDrive})
                    }
                </td>
                <td>
                    @foreach (var cmd in device.Device.Captures)
                    {
                        <div>@cmd.ToString()</div>
                    }
                </td>
                <td>
                    @Html.ActionLink("Usuń urządzenie", "DeleteDevice", new {id = device.Device.Id})
                </td>
            </tr>
        }
        <tr>
            <td style="text-align: center" colspan="6">
                @Html.ActionLink("Dodaj nowe urządzenie", "DeviceEdit", new { deviceId = 0 })
            </td>
        </tr>
    </table>

</div>

AmeWeb/Views/Home/Index.cshtml
@using System.Threading.Tasks
@using AmeWeb.Model
@model HomeViewModel
@{
    ViewData["Title"] = "AME Home Page";
}

<div class="row">
    <a asp-controller="Devices" asp-action="Index">Pokaż urządzenia</a>
    
    <table class="table table-bordered table-condensed">
        <tr>
            <th colspan="3">
                Zadania
            </th>
        </tr>
        @foreach (var task in Model.Tasks)
        {
            @Html.Partial("_TaskState", task)
        }
    </table>

    <form asp-action="CreateProject" asp-controller="Home">
        <table class="table table-bordered table-condensed">
            <tr>
                <th colspan="3">
                    Projekty
                </th>
            </tr>
            @foreach (var project in Model.Projects.OrderBy(p => p.EventDate))
            {
                <tr>
                    <td>@Html.ActionLink(project.UniqueName, "ShowAmeProject", new { projectPath = project.LocalPathRoot})</td>
                    <td>@project.LocalPathRoot</td>
                    <td>
                        @Html.ActionLink("Kopiuj karty", "Index", "CaptureCards", new { projectPath = project.LocalPathRoot })  
                    </td>
                </tr>
            }

            <tr>
                <td colspan="3">
                    katalog docelowy: @Html.ActionLink(Model.DestiantionRoot + "\\", "ChangeRootDirectory")
                    <input type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" name="ProjectDate"/>
                    <input type="text" value="Nazwa" name="ProjectName"/><input type="submit" value="utwórz nowy"/></td>
            </tr>
        </table>
        <img src="@Url.Action("Camera","Home")"/>
    </form>
</div>

AmeWeb/Views/Home/ShowAmeProject.cshtml
@using System.Threading.Tasks
@model AmeCommon.Model.AmeFotoVideoProject
@{
    ViewData["Title"] = "AME Home Page";
}

<div class="row">
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Projekt</th>
            <td>@Model.UniqueName</td>
        </tr>
        <tr>
            <th>Lokalizacja projektu</th>
            <td>@Model.LocalPathRoot</td>
        </tr>
    </table>
       
    <table class="table table-bordered table-condensed">
        <tr>
            <th colspan="4">Lista plików:</th>
        </tr>
        <tr>
            <th>Żródło</th>
            <th>Lokacja</th>
            <th>Suma kontrolna</th>
            <th>Wielkość pliku</th>
        </tr>
        @foreach (var fileInfo in Model.MediaFiles)
        {
            <tr>
                <td>@fileInfo.Source</td>
                <td>@fileInfo.RelativePath</td>
                <td>@fileInfo.CheckSum</td>
                <td>@(fileInfo.Size / 1024 / 1024) MB</td>
            </tr>
        }
    </table>
</div>

AmeWeb/Views/Home/ShowAmeTask.cshtml
@using AmeWeb.Model
@model AmeCommon.Tasks.BackgroundTask

<div id="main-task">
    <h3>@Model.Name</h3>
    <table class="table table-bordered table-condensed">
        <tr>
            <th>Stan</th>
            <td id="main-task-state">
                @AmeHelper.TaskStateImage(Model.State)
            </td>
        </tr>
        <tr>
            <th>Czasy</th>
            <td id="main-task-times">@Model.StarTime - @Model.EndTime</td>
        </tr>
        <tr id="maint-task-error" style="display: none">
            <th>Bład</th>
            <td id="maint-task-error-text">@Model.Error</td>
        </tr>
    </table>
    
    @if (Model.ChildTasks.Any())
    {
        <table class="table table-bordered table-condensed">
            <tr>
                <th colspan="2">Zadania składowe</th>
            </tr>
            <tr>
                <th>Nazwa</th>
                <th>Stan</th>
            </tr>

            @foreach (var task in Model.ChildTasks)
            {
                <tr>
                    <td>@task.Name</td>
                    <td id="child-task-@task.Id">@AmeHelper.TaskStateImage(task.State)</td>
                </tr>
            }
        </table>
    }
</div>
@section scripts{
    <script type="text/javascript">
        function refreshTaskState(state) {
            $('#main-task-state').html("<img height='20' src = '/images/task-state/" + state.state + ".gif' />");
            $('#main-task-times').html(state.times);
            for (var i = 0; i < state.childTasks.length; i++) {
                var ct = state.childTasks[i];
                $('#child-task-' + ct.id).html("<img height='20' src = '/images/task-state/" + ct.state + ".gif' />");
            }
        }

        function refreshTaskStateTick() {
            $.getJSON('@Url.Action("GetAmeTaskState", "Home")', { id: '@Model.Id' }, refreshTaskState);
        }

        $(function() {
            setInterval(refreshTaskStateTick, 3000);
        });
    </script>
}

AmeWeb/Views/Home/_TaskState.cshtml
@using AmeWeb.Model
@model AmeCommon.Tasks.BackgroundTask
<tr id="Task-@Model.Id" class="BackgroundTask">
    <td>@Html.ActionLink(Model.Name, "ShowAmeTask", new { Model.Id })</td>
    <td>message</td>
    <td>@AmeHelper.TaskStateImage(Model.State)</td>
</tr>

AmeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AmeWeb</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AmeWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - AmeWeb</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>